todo_app/tasks/urls.py
from django.urls import path
from . import views
app_name = "tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path('list', views.task_list, name="tasks_list"),
    path('form', views.create_task, name="form"),
    path('update_task/<str:pk>/', views.updateTask, name="update_tasks"),
    path('delete/<str:pk>/', views.deleteTask, name="delete_task")

]

todo_app/todo_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

todo_app/tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    desc = models.TextField(blank=True)
    status = models.BooleanField(default=False)
    task_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

todo_app/tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

todo_app/tasks/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
# Create your views here.
def index(request):
    return render(request, "index.html")

def task_list(request):
    tasks = Task.objects.all()

    context = {"tasks": tasks,

               }
    return render(request, "task_list.html", context)

def create_task(request):
    form = TaskForm()

    if request.method =="POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            form = TaskForm()
    context = {"form": form}
    return render(request, "form.html", context)

def updateTask(request, pk):

    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method=="POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/list')
    context = {'form': form}
    return render(request, 'update_task.html', context)
def deleteTask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method=="POST":
        item.delete()
        return redirect('/list')
    context = {'item': item}
    return render(request, 'delete.html', context)

todo_app/tasks/templates/delete.html
<p>Are you sure want to delete "{{item}}"?</p>
<form action="" method="post">
    {% csrf_token %}
    <button type="submit" name="confirm">DELETE</button>
</form>
<a href="{% url 'tasks:tasks_list' %}">Cancel</a>

todo_app/tasks/templates/form.html
<div class="row">
    <div class="col">
        <h2>Add item</h2>
        <form method="post" class="form-inline">
            {% csrf_token %}

            <div>Task: {{form.title}}</div>
            <div>Desc: {{form.desc}}</div>
            <input type="submit" value="save" name="Create Task">

        </form>
        <a href="{% url 'tasks:tasks_list' %}">TASKS LIST</a>
    </div>
</div>

todo_app/tasks/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello my friend</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">WELCOME! Here you can plan your task!</a>
    </nav>
<div align="center" class="container">
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item"><a href="{% url 'tasks:form' %}">ADD TASK</a></li>
        <li class="list-group-item"><a href="{% url 'tasks:tasks_list' %}">TASKS LIST</a></li>
</ul>
</div>
</body>
</html>

todo_app/tasks/templates/task_list.html
<title>Task list</title>
<body><h1 align="center">Task List</h1>

<div class="row">
    <div class="col">
        <ul class="list-group">
            {% for task in tasks %}

            <li class="list-group-item"><h3>{{task}}</h3>
                <div class="float-right">
                    <button type="submit" class="btn btn-danger mb-2"><a href="{% url 'tasks:update_tasks' task.id %}">UPDATE</a></button>
                    <button type="submit" class="btn btn-danger mb-2"><a href="{% url 'tasks:delete_task' task.id %}">DELETE</a></button>
                    {% if task.status == True %}
                    <strike>{{task}}</strike>
                    {% endif %}
                </div>

            </li>

            {% endfor %}

        </ul>
    </div>
</div>
</body>

todo_app/tasks/templates/update_task.html
<h1>Update task</h1>

<form method="post" action="">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="save" name="update_task">
</form>